import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import RenderProvider from "@/Context/visibility/RenderProvider";
import Navbar from "@/Components/Navbar";
import Cart from "@/Components/Cart";
import AOSInit from "../Components/AOS";
import "aos/dist/aos.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import AuthProvider from "../providers/AuthProvider";
import RenderModals from "@/Context/visibility/RenderModals";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Velvorn",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <AOSInit />
          <RenderProvider>
            <AuthProvider>
              <RenderModals />
              <Cart />
              <Navbar />
              {children}
            </AuthProvider>
          </RenderProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
