import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import RenderProvider from "@/Context/visibility/RenderProvider";
import Navbar from "@/Components/Navbar";
import Cart from "@/Components/Cart";
import AuthModals from "@/Context/visibility/AuthModals";
import { Box } from "@mui/material";
import AOSInit from "./AOS";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Velvorn",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AOSInit />
        <RenderProvider>
          <AuthModals />
          <Cart />
          <Navbar />
          {children}
        </RenderProvider>
      </body>
    </html>
  );
}
