import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import RenderProvider from "@/app/Context/visibility/RenderProvider";
import Navbar from "@/app/Components/Navbar";
import Cart from "@/app/Components/Cart";
import AuthModals from "@/app/Context/visibility/AuthModals";
import AOSInit from "./services/AOS";
import "aos/dist/aos.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Velvorn",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <AOSInit />
          <RenderProvider>
            <AuthModals />
            <Cart />
            <Navbar />
            {children}
          </RenderProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
